# Generated by Django 4.0.5 on 2022-06-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('avata', models.ImageField(default='default_dp', upload_to='uploads/')),
                ('name', models.CharField(max_length=30)),
                ('tel', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('registerd_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
