# Generated by Django 4.0.5 on 2022-07-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.TextField(max_length=100)),
                ('registerd_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
