# Generated by Django 4.0.5 on 2022-06-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_remove_pharmacy_logo_pharmacy_registerd_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='address',
            new_name='Location',
        ),
    ]
