# Generated by Django 4.0.5 on 2022-06-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_rename_address_pharmacy_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='owner',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
