# Generated by Django 4.0.5 on 2022-06-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_pharmacy_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='Location',
            new_name='location',
        ),
    ]
