# Generated by Django 4.0.5 on 2022-06-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_rename_location_pharmacy_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='registerd_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
