# Generated by Django 4.0.5 on 2022-06-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='no_medicine_image', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('generic_name', models.CharField(max_length=20)),
                ('packaging', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('price', models.IntegerField()),
                ('best_before', models.DateField()),
                ('status', models.CharField(default='Available', max_length=12)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.category')),
            ],
        ),
    ]
