# Generated by Django 4.0.5 on 2022-07-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_alter_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
