# Generated by Django 4.0.5 on 2022-07-01 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=30)),
                ('customer', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('items', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('trans_date', models.DateField(auto_now=True)),
                ('trans_by', models.ForeignKey(db_column='tran_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
