# Generated by Django 4.0.5 on 2022-06-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=30)),
                ('customer', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('items', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('trans_by', models.CharField(max_length=30)),
                ('trans_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
