# Generated by Django 4.0.5 on 2022-07-08 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='in_pharmacy',
            field=models.ForeignKey(db_column='in_pharmacy', on_delete=django.db.models.deletion.CASCADE, to='settings.pharmacy'),
        ),
    ]
