# Generated by Django 4.0.5 on 2022-07-07 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_initial'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='in_pharmacy',
            field=models.ForeignKey(db_column='in_pharmacy', default=1, on_delete=django.db.models.deletion.CASCADE, to='settings.pharmacy'),
            preserve_default=False,
        ),
    ]
