# Generated by Django 4.0.5 on 2022-07-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_records_in_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='contact',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='records',
            name='customer',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
