# Generated by Django 4.0.5 on 2022-07-01 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avata', models.ImageField(default='default_dp', upload_to='uploads/')),
                ('tel', models.CharField(blank=True, max_length=30)),
                ('work_for', models.ForeignKey(db_column='work_for', on_delete=django.db.models.deletion.CASCADE, related_name='work_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
