# Generated by Django 4.0.5 on 2022-06-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('avata', models.ImageField(default='default_dp', upload_to='uploads/')),
                ('name', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('title', models.CharField(default='owner', max_length=30)),
                ('work_for', models.CharField(default='self', max_length=30)),
                ('registerd_date', models.DateField(auto_now=True)),
                ('operate', models.CharField(default='active', max_length=30)),
            ],
        ),
    ]
