# Generated by Django 4.0.5 on 2022-07-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
