# Generated by Django 4.0.5 on 2022-06-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_remove_users_work_for_alter_users_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
