# Generated by Django 4.0.5 on 2022-07-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_alter_extenduser_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='tel',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
